Shv-libs4c library, add image updates, introduce abstraction in gen. code
This commit adds many changes to pysimCoder.
1) The whole SHV infrastructure has been reworked to a unified library
   called shv-libs4c. Basically, this library is based on the pysimCoder
   SHV routines, but now it's unified, provides transport layer
   abstraction (now, we support TCP/IP, only), provides platform
   abstraction (NuttX, Linux). In future, it could support more
   embedded devices and operating systems.

   Some old files were deleted in CodeGen/Common/shv, whereas some
   new were added - especially those responsible for the new SHV
   features.

2) Image update dialog has been added. Currently, there are 2 options.
   The first one is straightforward: using openocd to flash a device.
   This is applicable only to embedded devices.
   The second method are the SHV File node updates.
   Useful especially when working with NuttX when NXBoot is utilized.
   The dialog continously sends chunks of a new NuttX image to
   a NuttX device with some external storage, used as an update
   paritition by NXBoot. If the flashing is succesful
   (after a CRC check), the device is resetted. In the end, the image
   must be confirmed, as that is the part of the NXBoot API.

3) Big shv/generator.py rework. This is due to the firmware NXBoot
   updates. New nodes are added.

4) Overall rework and proof of concept of code generation.
   I've introduced the concept of model's context and manager.
   With this I'd want to rework all sources that it is possible
   to have multiple models running without any global variables.
   The manager is an abstract interface to the model, it allows
   to pause or resume the model's execution.

   The reason we want to pause the model's execution are
   the previously mentioned firmware updates. If a high task
   control loop is running with strict deadlines, some CPU
   load responsible for SHV communication and interaction
   with the update partition may cause these deadlines to
   be missed. It's just better to stop the model's execution
   at all, do some communication, and then restart (or resume).

5) Template makefile changes, where SHV is utilized (NuttX, LinuxRT)
   SHV cloning. Added stadartized makefile steps (CC, AR, ...)

Currently, nuttx.tmf, nuttx_timerhook.tmf, rt.tmf and rt_mz_apo.tmf
generated targets (i.e. the only supporting SHV) are stable.
Despite the fact that other targets should compile OK as there
are no changes to the core generator, these targets need to be
reworked aswell.

Signed-off-by: Stepan Pressl <pressl.stepan@gmail.com>

diff --git a/CodeGen/LinuxRT/devices/Makefile b/CodeGen/LinuxRT/devices/Makefile
--- a/CodeGen/LinuxRT/devices/Makefile
+++ b/CodeGen/LinuxRT/devices/Makefile
@@ -1,4 +1,4 @@
-all: dependencies allfiles lib install
+all: dependencies files allfiles lib install
 reduced: files lib install
 
 LIB = libpyblk.a
@@ -7,6 +7,9 @@ TARGET_INC = ../include
 INCLUDE = -I$(GENERIC_INC) -I$(TARGET_INC)
 COMMON_DIR = $(PYSUPSICTRL)/CodeGen/Common
 EXT_LIBS = $(PYSUPSICTRL)/ExtLibs
+SHV_COMPILED_INC_PATH = $(EXT_LIBS)/shv-libs4c-linux/_compiled/include
+SHV_COMPILED_LIB_PATH = $(EXT_LIBS)/shv-libs4c-linux/_compiled/lib
+SHV_REVISION = $(shell head -n1 "$(COMMON_DIR)/shv/shv-libs4c-revision.txt")
 
 .PHONY: all dependencies clean install allfiles
 
@@ -19,14 +22,10 @@ SRCALL += $(wildcard $(COMMON_DIR)/posix/*.c)
 SRCALL += $(wildcard $(COMMON_DIR)/AR2INO/*.c)
 
 ifeq ($(SHV),1)
-EXT_SHV_LIB = $(EXT_LIBS)/libshv/libshvchainpack/c
-
-SRCALL += $(EXT_SHV_LIB)/cchainpack.c $(EXT_SHV_LIB)/ccpcp.c \
-					$(EXT_SHV_LIB)/ccpcp_convert.c $(EXT_SHV_LIB)/ccpon.c 
-SRCALL += $(EXT_LIBS)/ulut/ulut/ul_gavlprim.c
-SRCALL += $(EXT_LIBS)/ulut/ulut/ul_gsacust.c
 SRCALL += $(wildcard $(COMMON_DIR)/shv/*.c)
 endif
+
+UNPACKLIB_DIR := $(PYSUPSICTRL)/CodeGen/LinuxRT/devices/unpacklib
 
 OBJ = $(notdir $(SRCALL:%.c=%.o))
 
@@ -44,8 +43,7 @@ DEFINES_LED = -D LED_SCRIPT=\"$(CWD)/led.py\"
 CC_FLAGS = -c $(DBG) $(INCLUDE)
 ifeq ($(SHV),1)
 CC_FLAGS += -I$(COMMON_DIR)/shv/include
-CC_FLAGS += -I$(EXT_LIBS)/libshv/libshvchainpack/c/include
-CC_FLAGS += -I$(EXT_LIBS)/ulut
+CC_FLAGS += -I$(SHV_COMPILED_INC_PATH)
 endif
 CC_FLAGS += -D CG_WITH_ENV_HOST_ADDR
 CC_FLAGS_SCP = -c $(DBG) $(INCLUDE)  $(DEFINES_SCP)
@@ -56,10 +54,27 @@ CC_FLAGS_FMU = -c $(DBG) $(INCLUDE) -Wall -DFMI_COSIMULATION \
 
 dependencies:
 ifeq ($(SHV),1)
-	cd $(EXT_LIBS) && if [ ! -e libshv ]; then git clone https://github.com/silicon-heaven/libshv; fi
-	cd $(EXT_LIBS) && if [ ! -e ulut ]; then git clone https://git.code.sf.net/p/ulan/ulut; fi
+	@ cd $(EXT_LIBS); \
+	if [ ! -e shv-libs4c-linux ]; then \
+		echo "Cloning shv-libs4c"; \
+		if ! git clone https://github.com/silicon-heaven/shv-libs4c shv-libs4c-linux > /dev/null 2>&1; then \
+			echo "Failed cloning the Silicon Heaven library, try again."; \
+		else \
+			( cd shv-libs4c-linux && \
+			  git checkout $(SHV_REVISION) && \
+			  git submodule update --recursive --init ) > /dev/null 2>&1; \
+			make -C shv-libs4c-linux CONFIG_SHV_LIBS4C_PLATFORM="linux" \
+				CC="$(CC)" \
+				CXX="$(CXX)" \
+				CFLAGS="$(CFLAGS)" \
+				CXXFLAGS="$(CXXFLAGS)" \
+				LD="$(LD)" \
+				LDFLAGS="$(LDFLAGS)" \
+				CONFIG_OC_ULUT_TESTS=n; \
+		fi \
+	fi
 endif
-	cd $(PYSUPSICTRL)/CodeGen/LinuxRT/devices
+	@cd $(PYSUPSICTRL)/CodeGen/LinuxRT/devices
 
 allfiles:
 
@@ -68,65 +83,76 @@ EXCLUDE = comedi_analog_input.c comedi_analog_output.c comedi_digital_input.c co
 SRC=$(filter-out $(EXCLUDE),$(SRCALL))
 
 scope.o: scope.c
-	$(CC) $(CC_FLAGS_SCP) $<
+	@echo "CC: $<"
+	@$(CC) $(CC_FLAGS_SCP) $<
 
 led.o: led.c
-	$(CC) $(CC_FLAGS_LED) $<
+	@echo "CC: $<"
+	@$(CC) $(CC_FLAGS_LED) $<
 
 FMUinterface.o: FMUinterface.c
-	$(CC) $(CC_FLAGS_FMU) $<
+	@echo "$CC: $<"
+	@$(CC) $(CC_FLAGS_FMU) $<
 
 %.o: %.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: $$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/CAN_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: CAN_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/common_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: common_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/Faulhaber_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: Faulhaber_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/Maxon_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: Maxon_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/posix/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: posix/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/AR2INO/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: AR2INO/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 ifeq ($(SHV),1)
-cchainpack.o: $(EXT_SHV_LIB)/cchainpack.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpcp.o: $(EXT_SHV_LIB)/ccpcp.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpcp_convert.o: $(EXT_SHV_LIB)/ccpcp_convert.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpon.o: $(EXT_SHV_LIB)/ccpon.c
-	$(CC) $(CC_FLAGS) $<
-
-ul_gavlprim.o: $(EXT_LIBS)/ulut/ulut/ul_gavlprim.c
-	$(CC) $(CC_FLAGS) $<
-
-ul_gsacust.o: $(EXT_LIBS)/ulut/ulut/ul_gsacust.c
-	$(CC) $(CC_FLAGS) $<
-
 %.o: $(COMMON_DIR)/shv/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: shv/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 endif
 
 lib: $(OBJ)
-	$(AR) -r $(LIB) $(OBJ)
+ifeq ($(SHV),1)
+	@ echo "AR: *.o"; \
+	echo "AR: libshvchainpack.a libshvtree.a libulut.a"; \
+	mkdir -p $(UNPACKLIB_DIR); \
+	cp $^ $(UNPACKLIB_DIR); \
+	cd $(UNPACKLIB_DIR); \
+	ar x $(SHV_COMPILED_LIB_PATH)/libshvchainpack.a; \
+	ar x $(SHV_COMPILED_LIB_PATH)/libshvtree.a; \
+	ar x $(SHV_COMPILED_LIB_PATH)/libulut.a; \
+	$(AR) rcs $(LIB) *.o; \
+	cp $(LIB) ..; \
+	rm -r $(UNPACKLIB_DIR)
+else
+	@echo "AR: *.o"
+	@$(AR) rcs $(LIB) $(OBJ)
+endif
 
 install:
-	mv $(LIB) ../lib
+	@echo "MV: $(LIB) -> PYSUPSICTRL/CodeGen/LinuxRT/lib/$(LIB)"
+	@mv $(LIB) ../lib
 
 clean:
-	rm -rf $(EXT_LIBS)/libshv
-	rm -rf $(EXT_LIBS)/ulut
-	rm -f $(LIB) $(OBJ)
+	@echo "RM: shv-libs4c-linux"
+	@echo "RM: $(LIB)"
+	@echo "RM: *.o"
+	@rm -rf $(EXT_LIBS)/shv-libs4c-linux
+	@rm -f $(LIB) $(OBJ)
diff --git a/CodeGen/linux_mz_apo/devices/Makefile b/CodeGen/linux_mz_apo/devices/Makefile
--- a/CodeGen/linux_mz_apo/devices/Makefile
+++ b/CodeGen/linux_mz_apo/devices/Makefile
@@ -7,6 +7,9 @@ TARGET_INC = ../include
 INCLUDE = -I$(GENERIC_INC) -I$(TARGET_INC)
 COMMON_DIR = $(PYSUPSICTRL)/CodeGen/Common
 EXT_LIBS = $(PYSUPSICTRL)/ExtLibs
+SHV_COMPILED_INC_PATH = $(EXT_LIBS)/shv-libs4c-linux/_compiled/include
+SHV_COMPILED_LIB_PATH = $(EXT_LIBS)/shv-libs4c-linux/_compiled/lib
+SHV_REVISION = $(shell head -n1 "$(COMMON_DIR)/shv/shv-libs4c-revision.txt")
 
 .PHONY: all dependencies clean install
 
@@ -18,14 +21,10 @@ SRCALL += $(wildcard $(COMMON_DIR)/Maxon_dev/*.c)
 SRCALL += $(wildcard $(COMMON_DIR)/posix/*.c)
 
 ifeq ($(SHV),1)
-EXT_SHV_LIB = $(EXT_LIBS)/libshv/libshvchainpack/c
-
-SRCALL += $(EXT_SHV_LIB)/cchainpack.c $(EXT_SHV_LIB)/ccpcp.c \
-					$(EXT_SHV_LIB)/ccpcp_convert.c $(EXT_SHV_LIB)/ccpon.c 
-SRCALL += $(EXT_LIBS)/ulut/ulut/ul_gavlprim.c
-SRCALL += $(EXT_LIBS)/ulut/ulut/ul_gsacust.c
 SRCALL += $(wildcard $(COMMON_DIR)/shv/*.c)
 endif
+
+UNPACKLIB_DIR := $(PYSUPSICTRL)/CodeGen/linux_mz_apo/devices/unpacklib
 
 CWD = $(shell pwd)
 
@@ -39,69 +38,91 @@ INCLUDE =  -I$(GENERIC_INC) -I$(TARGET_INC)
 CC_FLAGS = -c $(DBG) $(INCLUDE)
 ifeq ($(SHV),1)
 CC_FLAGS += -I$(COMMON_DIR)/shv/include
-CC_FLAGS += -I$(EXT_LIBS)/libshv/libshvchainpack/c/include
-CC_FLAGS += -I$(EXT_LIBS)/ulut
+CC_FLAGS += -I$(SHV_COMPILED_INC_PATH)
 endif
 CC_FLAGS += -D CG_WITH_ENV_HOST_ADDR
 
 dependencies:
 ifeq ($(SHV),1)
-	cd $(EXT_LIBS) && if [ ! -e libshv ]; then git clone https://github.com/silicon-heaven/libshv; fi
-	cd $(EXT_LIBS) && if [ ! -e ulut ]; then git clone https://git.code.sf.net/p/ulan/ulut; fi
+	@ cd $(EXT_LIBS); \
+	if [ ! -e shv-libs4c-linux ]; then \
+		echo "Cloning shv-libs4c"; \
+		if ! git clone https://github.com/silicon-heaven/shv-libs4c shv-libs4c-linux-mzapo > /dev/null 2>&1; then \
+			echo "Failed cloning the Silicon Heaven library, try again."; \
+		else \
+			( cd shv-libs4c-linux-mzapo && \
+			  git checkout $(SHV_REVISION) && \
+			  git submodule update --recursive --init ) > /dev/null 2>&1; \
+			make -C shv-libs4c-linux-mzapo CONFIG_SHV_LIBS4C_PLATFORM="linux" \
+				CC="$(CC)" \
+				CXX="$(CXX)" \
+				CFLAGS="$(CFLAGS)" \
+				CXXFLAGS="$(CXXFLAGS)" \
+				LD="$(LD)" \
+				LDFLAGS="$(LDFLAGS)" \
+				CONFIG_OC_ULUT_TESTS=n; \
+		fi \
+	fi
 endif
-	cd $(PYSUPSICTRL)/CodeGen/LinuxRT/devices
 
 SRC=$(filter-out $(EXCLUDE),$(SRCALL))
 OBJ = $(notdir $(SRCALL:.c=.o))
 
 %.o: %.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: $$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/CAN_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: CAN_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/common_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: common_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/Faulhaber_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: Faulhaber_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/Maxon_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: Maxon_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/posix/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: posix/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 ifeq ($(SHV),1)
-cchainpack.o: $(EXT_SHV_LIB)/cchainpack.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpcp.o: $(EXT_SHV_LIB)/ccpcp.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpcp_convert.o: $(EXT_SHV_LIB)/ccpcp_convert.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpon.o: $(EXT_SHV_LIB)/ccpon.c
-	$(CC) $(CC_FLAGS) $<
-
-ul_gavlprim.o: $(EXT_LIBS)/ulut/ulut/ul_gavlprim.c
-	$(CC) $(CC_FLAGS) $<
-
-ul_gsacust.o: $(EXT_LIBS)/ulut/ulut/ul_gsacust.c
-	$(CC) $(CC_FLAGS) $<
-
 %.o: $(COMMON_DIR)/shv/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: shv/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 endif
 
 lib: $(OBJ)
-	$(AR) -r $(LIB) $(OBJ)
+ifeq ($(SHV),1)
+	@ echo "AR: *.o"; \
+	echo "AR: libshvchainpack.a libshvtree.a libulut.a"; \
+	mkdir -p $(UNPACKLIB_DIR); \
+	cp $^ $(UNPACKLIB_DIR); \
+	cd $(UNPACKLIB_DIR); \
+	ar x $(SHV_COMPILED_LIB_PATH)/libshvchainpack.a; \
+	ar x $(SHV_COMPILED_LIB_PATH)/libshvtree.a; \
+	ar x $(SHV_COMPILED_LIB_PATH)/libulut.a; \
+	$(AR) rcs $(LIB) *.o; \
+	cp $(LIB) ..; \
+	rm -r $(UNPACKLIB_DIR)
+else
+	@echo "AR: *.o"
+	@$(AR) rcs $(LIB) $(OBJ)
+endif
 
 install:
-	mv $(LIB) ../lib
+	@echo "MV: $(LIB) -> PYSUPSICTRL/CodeGen/linux_mz_apo/lib/$(LIB)"
+	@mv $(LIB) ../lib
 
 clean:
-	rm -rf $(EXT_LIBS)/libshv
-	rm -rf $(EXT_LIBS)/ulut
-	rm -f $(LIB) $(OBJ)
+	@echo "RM: shv-libs4c-linux-mzapo"
+	@echo "RM: $(LIB)"
+	@echo "RM: *.o"
+	@rm -rf $(EXT_LIBS)/shv-libs4c-linux-mzapo
+	@rm -f $(LIB) $(OBJ)
diff --git a/CodeGen/nuttx/devices/Makefile b/CodeGen/nuttx/devices/Makefile
--- a/CodeGen/nuttx/devices/Makefile
+++ b/CodeGen/nuttx/devices/Makefile
@@ -8,6 +8,9 @@ INCLUDE =  -I$(GENERIC_INC) -I$(TARGET_INC)
 
 COMMON_DIR = $(PYSUPSICTRL)/CodeGen/Common
 EXT_LIBS = $(PYSUPSICTRL)/ExtLibs
+SHV_COMPILED_INC_PATH = $(EXT_LIBS)/shv-libs4c-nuttx/_compiled/include
+SHV_COMPILED_LIB_PATH = $(EXT_LIBS)/shv-libs4c-nuttx/_compiled/lib
+SHV_REVISION = $(shell head -n1 "$(COMMON_DIR)/shv/shv-libs4c-revision.txt")
 
 NUTTX_EXPORT = $(PWD)/../nuttx-export
 
@@ -24,15 +27,13 @@ SRCALL = $(wildcard $(COMMON_DIR)/common_dev/*.c)
 SRCALL += $(wildcard $(COMMON_DIR)/posix/*.c)
 SRCALL += serialOut.c
 
+# Add the pysimCoder SHV adaptation sources
 ifeq ($(SHV),1)
-EXT_SHV_LIB = $(EXT_LIBS)/libshv/libshvchainpack/c
-
-SRCALL += $(EXT_SHV_LIB)/cchainpack.c $(EXT_SHV_LIB)/ccpcp.c \
-					$(EXT_SHV_LIB)/ccpcp_convert.c $(EXT_SHV_LIB)/ccpon.c 
-SRCALL += $(EXT_LIBS)/ulut/ulut/ul_gavlprim.c
-SRCALL += $(EXT_LIBS)/ulut/ulut/ul_gsacust.c
 SRCALL += $(wildcard $(COMMON_DIR)/shv/*.c)
 endif
+
+SHV_IN_NUTTX := $(shell grep -wc "CONFIG_NETUTILS_LIBSHVC" $(NUTTX_EXPORT)/include/nuttx/config.h)
+UNPACKLIB_DIR := $(PYSUPSICTRL)/CodeGen/nuttx/devices/unpacklib
 
 ifeq ($(CONFIG_ADC),y)
 SRCALL += nuttx_ADC.c
@@ -129,22 +130,47 @@ CXXFLAGS = $(TARGET_ARCH_FLAGS) $(ARCHCXXFLAGS) $(ARCHWARNINGSXX) $(OPT_OPTS) $(
 OBJEX = $(SRC:.c=.o)
 DEFINES = -D PLOTTER_SCRIPT=\"$(CWD)/scope.py\"
 CC_FLAGS = -c $(DBG) $(INCLUDE) $(CFLAGS)
+# Include the SHV include directories. Expect the headers at this exact location.
 ifeq ($(SHV),1)
+ifeq ($(SHV_IN_NUTTX),0)
+CC_FLAGS += -I$(SHV_COMPILED_INC_PATH)
+endif
 CC_FLAGS += -I$(COMMON_DIR)/shv/include
-CC_FLAGS += -I$(EXT_LIBS)/libshv/libshvchainpack/c/include
-CC_FLAGS += -I$(EXT_LIBS)/ulut
 endif
 CC_FLAGS_SCP = -c $(DBG) $(INCLUDE) $(CFLAGS) $(DEFINES)
 CC_FLAGS_FMU = -c $(DBG) $(INCLUDE) $(CFLAGS) -Wall -DFMI_COSIMULATION \
                              -DSTANDALONE_XML_PARSER -DLIBXML_STATIC \
                               -I$(FMUDIR)/fmuinc/include -I$(FMUDIR)/fmuinc/parser -I$(FMUDIR)/fmuinc
 
+# Decide what SHV version we pick. In case the NuttX export has no SHV support,
+# we clone the SHV as an external library and pack it inside $(LIB).
 dependencies:
 ifeq ($(SHV),1)
-	cd $(EXT_LIBS) && if [ ! -e libshv ]; then git clone https://github.com/silicon-heaven/libshv; fi
-	cd $(EXT_LIBS) && if [ ! -e ulut ]; then git clone https://git.code.sf.net/p/ulan/ulut; fi
+	@if [ "$(SHV_IN_NUTTX)" -lt 1 ]; then \
+		echo "Silicon Heaven library was not found in NuttX, using a cloned one."; \
+		cd $(EXT_LIBS); \
+		if [ ! -e shv-libs4c-nuttx ]; then \
+			if ! git clone https://github.com/silicon-heaven/shv-libs4c shv-libs4c-nuttx > /dev/null 2>&1; then \
+				echo "Failed cloning the Silicon Heaven library, try again."; \
+			else \
+				( cd shv-libs4c-nuttx && \
+				  git checkout $(SHV_REVISION) && \
+				  git submodule update --recursive --init ) > /dev/null 2>&1; \
+				make -C shv-libs4c-nuttx CONFIG_SHV_LIBS4C_PLATFORM="nuttx" \
+					CC="$(CC)" \
+					CXX="$(CXX)" \
+					CFLAGS="$(CFLAGS)" \
+					CXXFLAGS="$(CXXFLAGS)" \
+					LD="$(LD)" \
+					LDFLAGS="$(LDFLAGS)" \
+					CONFIG_OC_ULUT_TESTS=n; \
+			fi \
+		fi \
+	else \
+		echo "Using the Silicon Heaven library from the NuttX build."; \
+	fi
 endif
-	cd $(PYSUPSICTRL)/CodeGen/nuttx/devices
+	@cd $(PYSUPSICTRL)/CodeGen/nuttx/devices
 
 allfiles:
 
@@ -159,60 +185,70 @@ FMUinterface.o: FMUinterface.c
 	$(CC) $(CC_FLAGS_FMU) $<
 
 %.o: %.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: $$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: sensors/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: sensors/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 ifeq ($(SHV),1)
-cchainpack.o: $(EXT_SHV_LIB)/cchainpack.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpcp.o: $(EXT_SHV_LIB)/ccpcp.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpcp_convert.o: $(EXT_SHV_LIB)/ccpcp_convert.c
-	$(CC) $(CC_FLAGS) $<
-
-ccpon.o: $(EXT_SHV_LIB)/ccpon.c
-	$(CC) $(CC_FLAGS) $<
-
-ul_gavlprim.o: $(EXT_LIBS)/ulut/ulut/ul_gavlprim.c
-	$(CC) $(CC_FLAGS) $<
-
-ul_gsacust.o: $(EXT_LIBS)/ulut/ulut/ul_gsacust.c
-	$(CC) $(CC_FLAGS) $<
-
 %.o: $(COMMON_DIR)/shv/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: shv/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 endif
 
-%.o: $(COMMON_DIR)/shv/%.c
-	$(CC) $(CC_FLAGS) $<
-
 %.o: $(COMMON_DIR)/CAN_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: CAN_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/common_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: common_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/Faulhaber_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: Faulhaber_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/Maxon_dev/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: Maxon_dev/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 %.o: $(COMMON_DIR)/posix/%.c
-	$(CC) $(CC_FLAGS) $<
+	@echo "CC: posix/$$(basename $<)"
+	@$(CC) $(CC_FLAGS) $<
 
 lib: $(OBJ)
-	$(AR) $(LIB) $(OBJ)
+ifeq ($(SHV),1)
+	@ if [ "$(SHV_IN_NUTTX)" -lt 1 ]; then \
+		echo "AR: *.o"; \
+		echo "AR: libshvchainpack.a libshvtree.a libulut.a"; \
+		mkdir -p $(UNPACKLIB_DIR); \
+		cp $^ $(UNPACKLIB_DIR); \
+		cd $(UNPACKLIB_DIR); \
+		ar x $(SHV_COMPILED_LIB_PATH)/libshvchainpack.a; \
+		ar x $(SHV_COMPILED_LIB_PATH)/libshvtree.a; \
+		ar x $(SHV_COMPILED_LIB_PATH)/libulut.a; \
+		$(AR) $(LIB) *.o; \
+		cp $(LIB) ..; \
+		rm -r $(UNPACKLIB_DIR); \
+	else \
+		echo "AR: *.o"; \
+		$(AR) $(LIB) $(OBJ); \
+	fi
+else
+	@echo "AR: *.o"
+	@$(AR) $(LIB) $(OBJ)
+endif
 
 install:
-	mkdir -p ../lib
-	mv $(LIB) ../lib
+	@mkdir -p ../lib
+	@echo "MV: $(LIB) -> PYSUPSICTRL/CodeGen/nuttx/lib/$(LIB)"
+	@mv $(LIB) $(PYSUPSICTRL)/CodeGen/nuttx/lib
 
 clean:
-	rm -rf $(EXT_LIBS)/libshv
-	rm -rf $(EXT_LIBS)/ulut
-	rm -f $(LIB) $(OBJ)
+	@echo "RM: shv-libs4c-nuttx"
+	@echo "RM: $(LIB)"
+	@echo "RM: *.o"
+	@rm -rf $(EXT_LIBS)/shv-libs4c-nuttx
+	@rm -f $(LIB) $(OBJ)
